In [1]:
import pandas as pd

In [5]:
isco_groups = pd.read_csv('ESCO_data/ISCOGroups.csv').fillna('')

In [9]:
isco_groups

,ORIGINURI,ID,UUIDHISTORY,CODE,PREFERREDLABEL,ALTLABELS,DESCRIPTION
0,http://data.europa.eu/esco/isco/C0,key_1,375ad4ae-0113-4d76-b42a-e7b9ad8178bd,0,Armed forces occupations,,Armed forces occupations include all jobs held...
1,http://data.europa.eu/esco/isco/C01,key_2,cf84519f-ff3c-459c-b5f7-7221c4261e00,1,Commissioned armed forces officers,,Commissioned armed forces officers provide lea...
2,http://data.europa.eu/esco/isco/C011,key_3,4cbf6d83-8d95-484b-80c5-fc2b3ea556f5,11,Commissioned armed forces officers,,Commissioned armed forces officers provide lea...
3,http://data.europa.eu/esco/isco/C0110,key_4,3f6ce529-1673-4957-a404-6da3ea6d68a5,110,Commissioned armed forces officers,,Commissioned armed forces officers provide lea...
4,http://data.europa.eu/esco/isco/C02,key_5,92d2f425-b38f-422b-ac9e-37bf20328fb3,2,Non-commissioned armed forces officers,,Non-commissioned armed forces officers enforce...
...,...,...,...,...,...,...,...
614,http://data.europa.eu/esco/isco/C9621,key_615,bada6312-a77c-462a-8dc8-370915fa443d,9621,"Messengers, package deliverers and luggage por...",,"Messengers, package deliverers and luggage por..."
615,http://data.europa.eu/esco/isco/C9622,key_616,37fd67bf-333d-4feb-9344-699171fbf7a7,9622,Odd job persons,,"Odd-job persons clean, paint and maintain buil..."
616,http://data.europa.eu/esco/isco/C9623,key_617,c8cfc2f5-eedf-488e-b967-a725473051df,9623,Meter readers and vending-machine collectors,,Meter readers and vending-machine collectors s...
617,http://data.europa.eu/esco/isco/C9624,key_618,dce222e2-80d5-46a3-8819-981b95f5dc70,9624,Water and firewood collectors,,Water and firewood collectors collect water an...
618,http://data.europa.eu/esco/isco/C9629,key_619,dec07463-d641-4823-b782-e58c63e39951,9629,Elementary workers not elsewhere classified,,This unit group covers elementary workers not ...

In [13]:
class Neo4jQueryBuilder:
    @staticmethod
    def build_occupations_nodes_query(row):
        return f"""
        MERGE (c:Occupation {{key_id: '{row.get('ID', '')}'}})  
        ON CREATE SET 
          c.occupation_name = "{row.get('PREFERREDLABEL', '').replace('"','')}",
          c.origin_url = coalesce('{row.get('ORIGINURI', '')}', ""),
          c.code = coalesce('{row.get('CODE', '')}', ""),
          c.description = coalesce("{row.get('DESCRIPTION', '').replace('"','')}", "")
        """

    @staticmethod
    def build_isko_group_node_query(row):
        return f"""
        MERGE (c:ISCO_group {{key_id: '{row.get('ID', '')}'}})  
        ON CREATE SET 
          c.occupation_name = "{row.get('PREFERREDLABEL', '').replace('"','')}",
          c.origin_url = coalesce('{row.get('ORIGINURI', '')}', ""),
          c.code = coalesce('{row.get('CODE', '')}', ""),
          c.description = coalesce("{row.get('DESCRIPTION', '').replace('"','')}", "")
        """

    @staticmethod
    def build_occupation_hierarchy_query(row):
        return f"""
        MATCH (a:Occupation {{key_id: '{row.get('PARENTID', '')}'}}) ,(b:Occupation {{key_id: '{row.get('CHILDID', '')}'}})
        MERGE (a)<-[r:HAS_PARENT_OCCUPATION]-(b)
        """

    @staticmethod
    def build_skill_nodes_query(row):
        return f"""
        MERGE (c:Skill {{key_id: '{row.get('ID', '')}'}})  
        ON CREATE SET 
          c.skill_name = "{row.get('PREFERREDLABEL', '').replace('"','')}",
          c.origin_url = coalesce('{row.get('ORIGINURI', '')}', ""),
          c.skill_type = coalesce('{row.get('SKILLTYPE', '')}', ""),
          c.description = coalesce("{row.get('DESCRIPTION', '').replace('"','')}", "")
        """

    @staticmethod
    def build_skill_occupation_hierarchy(row):
        return f"""
        MATCH (a:Occupation {{key_id: '{row.get('OCCUPATIONID', '')}'}}) ,(b:Skill {{key_id: '{row.get('SKILLID', '')}'}})
        MERGE (a)-[r:HAS_SKILL]->(b)
        SET r.type = '{row.get('RELATIONTYPE', '')}'
        """